<?php

/**
 * Tests for the dmTicket mapper.
 *
 * They cover the three defects fixed on that mapper, each one falsifiable:
 * neutralise the fix and the matching test goes red.
 *
 *   1. note_public / note_private / email_from were published (and the two
 *      notes were writable) although llx_ticket has no such column and
 *      Ticket::update() never writes them -- a write answered 200 and lost the
 *      value. testGhostColumnsDoNotExistInLlxTicket proves the premise against
 *      the real schema, so the removal cannot be a guess.
 *   2. the published `status` key addresses the PHP property Ticket::fetch()
 *      aliases from fk_statut, which the catalog derivation cannot see, so the
 *      status filter and sort were silently dropped. The two SQL tests below
 *      assert the produced fragments really name fk_statut.
 *   3. creation through the generic facade is impossible (ref required, not
 *      generated by create(), not writable, no pre-create hook).
 *
 * Copyright (c) 2026 Eric Seigne <eric.seigne@cap-rel.fr>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

namespace SmartAuth\Tests\IntegrationDolibarr;

use SmartAuth\DolibarrMapping\dmTicket;
use SmartAuth\DolibarrMapping\MapperValidationException;
use SmartAuth\Api\ObjectRegistry;
use ReflectionClass;

require_once DOL_DOCUMENT_ROOT . '/ticket/class/ticket.class.php';

/**
 * Test double exposing the protected catalog-driven builders of
 * PaginatedListTrait, so the SQL a real list query would emit can be asserted.
 */
class DmTicketListProbe
{
    use \SmartAuth\Api\PaginatedListTrait;

    public function filters(array $params, $mapper, $alias)
    {
        return $this->buildSqlFiltersFromCatalog($params, $mapper, $alias);
    }

    public function sort(array $params, $mapper, $alias, $default)
    {
        return $this->buildSortClauseFromCatalog($params, $mapper, $alias, $default);
    }

    public function parse($arr)
    {
        return $this->parseListParams($arr);
    }
}

/**
 * @covers \SmartAuth\DolibarrMapping\dmTicket
 */
class DmTicketTest extends DolibarrRealTestCase
{
    /** @var dmTicket */
    private $mapper;

    /** @var DmTicketListProbe */
    private $probe;

    protected function setUp(): void
    {
        parent::setUp();
        $this->ensureTicketTable();
        $this->mapper = new dmTicket();
        $this->probe = new DmTicketListProbe();
    }

    /* -----------------------------------------------------------------
     * Defect 1 -- the ghost columns
     * --------------------------------------------------------------- */

    /**
     * Premise of the whole removal, asserted against the schema actually
     * loaded in the harness rather than against the SQL file: if any of these
     * three columns existed, dropping the keys would be a regression.
     */
    public function testGhostColumnsDoNotExistInLlxTicket(): void
    {
        $columns = $this->ticketColumns();

        $this->assertNotEmpty($columns, 'llx_ticket introspection returned no column');
        $this->assertContains('subject', $columns, 'sanity check: llx_ticket must expose its real columns');

        foreach (['note_public', 'note_private', 'email_from'] as $ghost) {
            $this->assertNotContains(
                $ghost,
                $columns,
                $ghost . ' now exists in llx_ticket: dmTicket must publish it again'
            );
        }
    }

    /**
     * Read side: the three keys are gone from the published mapping, so they
     * can no longer show up as always-empty columns in a column catalog.
     */
    public function testGhostKeysAreNoLongerPublished(): void
    {
        $published = $this->publishedFields();

        foreach (['note_public', 'note_private', 'email_from'] as $ghost) {
            $this->assertArrayNotHasKey($ghost, $published);
        }

        $desc = $this->mapper->objectDesc();
        foreach (['public_note', 'private_note', 'email_from'] as $apiKey) {
            $this->assertObjectNotHasProperty($apiKey, $desc);
        }
    }

    /**
     * Write side, and the actual behaviour change: a note write used to be
     * accepted and silently dropped. It is now rejected with a named error.
     */
    public function testWritingANoteIsRejectedInsteadOfSilentlyIgnored(): void
    {
        foreach (['public_note', 'private_note'] as $apiKey) {
            try {
                $this->mapper->importMappedData([$apiKey => 'lost in the void']);
                $this->fail('Expected MapperValidationException for ' . $apiKey);
            } catch (MapperValidationException $e) {
                $this->assertArrayHasKey($apiKey, $e->getErrors());
            }
        }
    }

    /**
     * The generic guard that would have caught the original bug on its own:
     * anything declared writable must be a real column of llx_ticket, since
     * Ticket::update() only ever writes columns.
     */
    public function testEveryWritableFieldIsARealColumnOfLlxTicket(): void
    {
        $columns = $this->ticketColumns();
        $writable = $this->writableFields();

        $this->assertNotEmpty($writable);
        foreach ($writable as $field) {
            $this->assertContains(
                $field,
                $columns,
                "writable field '" . $field . "' has no column in llx_ticket: writing it would be a silent no-op"
            );
        }
    }

    /**
     * The registry entry documents itself as mirroring the mapper allowlist.
     * Kept in step here so the two never drift again.
     */
    public function testRegistryAllowedFieldsMirrorWritableFields(): void
    {
        $builtins = ObjectRegistry::builtins();
        $this->assertArrayHasKey('ticket', $builtins);

        $allowed = $builtins['ticket']['allowed_fields'];
        sort($allowed);
        $writable = $this->writableFields();
        sort($writable);

        $this->assertSame($writable, $allowed);
    }

    /* -----------------------------------------------------------------
     * Defect 2 -- filter, sort and free-text search
     * --------------------------------------------------------------- */

    /**
     * The core of the fix: a status filter must reach the fk_statut column.
     * Without getFilterableColumns() the catalog marks `status` non filterable
     * (its doliside is a PHP property, absent from Ticket::$fields) and the
     * fragment comes back empty.
     */
    public function testStatusFilterTargetsTheFkStatutColumn(): void
    {
        $params = $this->probe->parse(['filter' => ['status' => (string) \Ticket::STATUS_CLOSED]]);
        list($where) = $this->probe->filters($params, $this->mapper, 'tk');

        $this->assertStringContainsString('tk.fk_statut = 8', $where);
        $this->assertStringNotContainsString('tk.status', $where, 'tk.status is not a column of llx_ticket');
    }

    /**
     * Same for the sort axis. `status` sorts on fk_statut, and the non
     * whitelisted keys still fall back to the default clause.
     */
    public function testStatusSortTargetsTheFkStatutColumn(): void
    {
        $params = $this->probe->parse(['sort' => 'status', 'order' => 'desc']);
        $clause = $this->probe->sort($params, $this->mapper, 'tk', 'tk.rowid DESC');

        $this->assertSame(' ORDER BY tk.fk_statut DESC', $clause);
    }

    /**
     * A JOIN result has no column to sort on: asking for it must degrade to
     * the default clause, never emit "ORDER BY tk.type_label".
     */
    public function testSortingOnAJoinedLabelFallsBackToTheDefaultClause(): void
    {
        $params = $this->probe->parse(['sort' => 'typeLabel', 'order' => 'asc']);
        $clause = $this->probe->sort($params, $this->mapper, 'tk', 'tk.rowid DESC');

        $this->assertSame(' ORDER BY tk.rowid DESC', $clause);
    }

    /**
     * Every column named by the two maps must exist, otherwise the list query
     * dies on "Unknown column" -- the exact failure mode the maps exist to
     * prevent.
     */
    public function testFilterAndSortMapsOnlyNameRealColumns(): void
    {
        $columns = $this->ticketColumns();

        // Guard against the vacuous pass: an empty map would satisfy every
        // foreach below while having silently dropped the whole fix.
        $this->assertNotEmpty($this->mapper->getFilterableColumns());
        $this->assertNotEmpty($this->mapper->getSortableColumns());

        foreach ($this->mapper->getFilterableColumns() as $apiKey => $def) {
            $this->assertContains(
                $def['column'],
                $columns,
                "filterable '" . $apiKey . "' points at a missing column '" . $def['column'] . "'"
            );
        }
        foreach ($this->mapper->getSortableColumns() as $apiKey => $column) {
            $this->assertContains(
                $column,
                $columns,
                "sortable '" . $apiKey . "' points at a missing column '" . $column . "'"
            );
        }
    }

    /**
     * The maps are keyed on the CAMEL CASE catalog keys the frontend sends
     * (dmBase converts the appside name through snakeToCamel). Keying them on
     * the snake_case appside is a silent no-op: the filter is simply never
     * matched.
     */
    public function testFilterAndSortKeysAreCatalogKeys(): void
    {
        $expected = [];
        foreach ($this->publishedFields() as $appside) {
            if ($appside === 'id') {
                continue;
            }
            $expected[$this->camelize($appside)] = true;
        }

        foreach (array_keys($this->mapper->getFilterableColumns()) as $key) {
            $this->assertArrayHasKey($key, $expected, "filter key '" . $key . "' is not a catalog key");
        }
        foreach (array_keys($this->mapper->getSortableColumns()) as $key) {
            $this->assertArrayHasKey($key, $expected, "sort key '" . $key . "' is not a catalog key");
        }
    }

    /**
     * Free-text search runs on the columns Dolibarr itself searches (the
     * 'searchall' => 1 entries of Ticket::$fields, minus the integer foreign
     * key), and on nothing else.
     */
    public function testSearchFieldsAreTheCoreSearchallColumns(): void
    {
        $this->assertSame(
            ['ref', 'track_id', 'subject', 'origin_email'],
            $this->mapper->getSearchFields()
        );

        $columns = $this->ticketColumns();
        foreach ($this->mapper->getSearchFields() as $field) {
            $this->assertContains($field, $columns);
        }
    }

    /**
     * Falsification of the previous test: without the override, the dmBase
     * fallback ("every varchar of $fields, unless some field declares
     * `searchable`") would have dragged the dictionary codes in. Both premises
     * of that fallback are asserted here, so the override cannot be dismissed
     * as defensive noise.
     */
    public function testTheDerivationWouldHavePulledInDictionaryCodes(): void
    {
        $fields = (new \Ticket($this->db))->fields;

        foreach ($fields as $name => $def) {
            $this->assertArrayNotHasKey(
                'searchable',
                $def,
                "Ticket::\$fields['" . $name . "'] now declares 'searchable': dmBase would honour it strictly"
            );
        }

        foreach (['type_code', 'category_code', 'severity_code'] as $code) {
            $this->assertArrayHasKey($code, $fields);
            $this->assertStringStartsWith('varchar', (string) $fields[$code]['type']);
            $this->assertNotContains(
                $code,
                $this->mapper->getSearchFields(),
                $code . ' is a dictionary code, searching free text through it matches unrelated tickets'
            );
        }
    }

    /* -----------------------------------------------------------------
     * Defect 3 -- creation cannot go through the facade
     * --------------------------------------------------------------- */

    /**
     * The whole reason the consuming module owns a local POST route.
     * Ticket::create() refuses an empty ref, and the facade has no way to fill
     * it: `ref` is not writable, so the payload cannot carry it either.
     */
    public function testCreateWithoutARefIsRefusedAndRefIsNotWritable(): void
    {
        $ticket = new \Ticket($this->db);
        $ticket->subject = 'No ref on purpose';
        $ticket->message = 'Facade create path';
        $ticket->fk_user_create = (int) $this->testUser->id;

        $res = $ticket->create($this->testUser);
        $this->assertSame(-3, $res, 'Ticket::create() must return -3 when verify() rejects the empty ref');
        $this->assertContains('ErrorTicketRefRequired', (array) $ticket->errors);

        try {
            $this->mapper->importMappedData(['ref' => 'FORGED-REF']);
            $this->fail('Expected MapperValidationException for ref');
        } catch (MapperValidationException $e) {
            $this->assertArrayHasKey('ref', $e->getErrors());
        }
    }

    /**
     * The local route replays what the native REST API does: getDefaultRef()
     * then create(). Asserted here so the mapper documentation stays honest
     * about the supported creation path.
     */
    public function testCreateSucceedsOnceTheDefaultRefIsSet(): void
    {
        $ticket = $this->createTicket(['subject' => 'Created with a default ref']);

        $this->assertNotEmpty($ticket->ref);
        $this->assertNotEmpty($ticket->track_id, 'create() generates track_id when blank');
    }

    /* -----------------------------------------------------------------
     * Round trip
     * --------------------------------------------------------------- */

    /**
     * End-to-end read: the status survives the fetch() rename, and none of the
     * removed keys reappears in a real payload.
     */
    public function testExportCarriesStatusAndNoGhostKey(): void
    {
        $societe = $this->createTestSociete(['name' => 'Ticket customer']);
        $ticket = $this->createTicket([
            'subject'       => 'Round-trip ticket',
            'message'       => 'Issue described in plain text',
            'fk_soc'        => (int) $societe->id,
            'severity_code' => 'NORMAL',
        ]);

        $fresh = new \Ticket($this->db);
        $this->assertSame(1, $fresh->fetch($ticket->id));

        $payload = $this->mapper->exportMappedData($fresh);

        $this->assertSame((int) $ticket->id, (int) $payload->id);
        $this->assertSame('Round-trip ticket', $payload->subject);
        $this->assertSame((int) $societe->id, (int) $payload->thirdparty);
        // fetch() SELECTs "t.fk_statut as status": a mapper reading fk_statut
        // straight from the object would still work here (the class mirrors the
        // value for backward compatibility) but would export nothing on a raw
        // row. The published key is `status`.
        $this->assertObjectHasProperty('status', $payload);
        $this->assertSame(\Ticket::STATUS_NOT_READ, (int) $payload->status);

        foreach (['public_note', 'private_note', 'email_from'] as $ghost) {
            $this->assertObjectNotHasProperty($ghost, $payload);
        }
    }

    /* -----------------------------------------------------------------
     * Helpers
     * --------------------------------------------------------------- */

    /**
     * Create a persisted ticket the way the local POST route does.
     */
    private function createTicket(array $data): \Ticket
    {
        $ticket = new \Ticket($this->db);
        $ticket->subject = $data['subject'] ?? 'Test ticket';
        $ticket->message = $data['message'] ?? 'Test message';
        $ticket->type_code = $data['type_code'] ?? 'OTHER';
        $ticket->category_code = $data['category_code'] ?? 'OTHER';
        $ticket->severity_code = $data['severity_code'] ?? 'NORMAL';
        $ticket->fk_user_create = (int) $this->testUser->id;
        if (!empty($data['fk_soc'])) {
            $ticket->fk_soc = (int) $data['fk_soc'];
        }
        // Ticket::create() does NOT generate the reference; getDefaultRef()
        // does, and nothing calls it from create().
        $ticket->ref = $ticket->getDefaultRef();

        $id = $ticket->create($this->testUser);
        $this->assertGreaterThan(0, $id, 'failed to create ticket: ' . implode(',', (array) $ticket->errors));

        return $ticket;
    }

    /**
     * Column names of llx_ticket as the harness really loaded them.
     *
     * @return string[]
     */
    private function ticketColumns(): array
    {
        $out = [];
        $resql = $this->db->query('PRAGMA table_info(' . MAIN_DB_PREFIX . 'ticket)');
        if (!$resql) {
            $this->fail('could not introspect ' . MAIN_DB_PREFIX . 'ticket: ' . $this->db->lasterror());
        }
        while ($obj = $this->db->fetch_object($resql)) {
            $out[] = (string) $obj->name;
        }
        $this->db->free($resql);

        return $out;
    }

    /**
     * @return array<string,string> doliside => appside
     */
    private function publishedFields(): array
    {
        $prop = (new ReflectionClass(dmTicket::class))->getProperty('listOfPublishedFields');
        $prop->setAccessible(true);

        return (array) $prop->getValue($this->mapper);
    }

    /**
     * @return string[]
     */
    private function writableFields(): array
    {
        $prop = (new ReflectionClass(dmTicket::class))->getProperty('writableFields');
        $prop->setAccessible(true);

        return (array) $prop->getValue($this->mapper);
    }

    /**
     * Local copy of dmBase::snakeToCamel (private static there), so the test
     * checks the maps against the conversion rule and not against itself.
     */
    private function camelize(string $key): string
    {
        if (strpos($key, '_') === false) {
            return $key;
        }
        $parts = explode('_', $key);
        $first = array_shift($parts);

        return $first . implode('', array_map('ucfirst', $parts));
    }

    /**
     * The dolibarr-integration-sqlite baseline does not ship llx_ticket; load
     * it from the Dolibarr install SQL so the DB-backed assertions really run.
     * Same helper as MapperRoundTripLotBTest.
     */
    private function ensureTicketTable(): void
    {
        $prefix = MAIN_DB_PREFIX;
        $sql = "SELECT name FROM sqlite_master WHERE type='table' AND name = '" . $prefix . "ticket'";
        $resql = $this->db->query($sql);
        if ($resql && $this->db->fetch_object($resql)) {
            return; // already present
        }

        require_once DOL_DOCUMENT_ROOT . '/core/lib/admin.lib.php';
        $dir = DOL_DOCUMENT_ROOT . '/install/mysql/tables/';
        foreach ([
            'llx_ticket-ticket.sql',
            'llx_ticket_extrafields-ticket.sql',
            'llx_categorie_ticket-ticket.sql',
        ] as $file) {
            $res = run_sql($dir . $file, 1, 0, 0);
            if ($res <= 0) {
                $this->markTestSkipped(
                    'Could not create ' . $file . ' on the SQLite baseline (run_sql returned ' . $res . ').'
                );
            }
        }

        $resql = $this->db->query($sql);
        if (!$resql || !$this->db->fetch_object($resql)) {
            $this->markTestSkipped('llx_ticket still missing after run_sql on the SQLite baseline.');
        }
    }
}
