#!/usr/bin/make
# makefile for cap-rel projects
#

SHELL = bash
MODULE = smartauth

.DEFAULT_GOAL := help

help:
	@echo 'Available commands:'
	@echo -e 'zip \t\t — \t build zip file'

zip:
	(php ./build/buildzip.php)

apidoc:
	apidoc -i api/ -o /tmp/apidoc -c api/apidoc.json -f ".*.php"
	# rsync -avP /tmp/apidoc/ z.cap-rel.fr://home/webs/z.cap-rel.fr/htdocs/doc/