#!/usr/bin/make
# makefile for cap-rel projects
#

SHELL = bash
MODULE = smartauth

.DEFAULT_GOAL := help

help:
	@echo 'Available commands:'
	@echo -e 'zip \t\t — \t build zip file'

zip:
	(php ./build/buildzip.php)

apidoc:
	# apidoc -i api/ -o ./documentation -c api/apidoc.json -f ".*.php"
	apidoc-markdown -i api/ -o ./documentation/doc.md -c api/apidoc.json -f ".*.php"
