-- Migration: add per-user idempotency cache for POST /upload.
--
-- Lets a PWA recover the original upload_id when retrying an upload after
-- a 2xx response was lost on the wire, instead of creating a duplicate
-- file on the filesystem.
--
